# Generated by Django 5.1.1 on 2024-10-26 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestionLangue", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SortieVoice",
        ),
        migrations.DeleteModel(
            name="Voice",
        ),
    ]
